### ISSUE TITLE
Backslashes shouldn't escape quotes

### ISSUE THREAD

**Issue by femboyfin** [joelcancela/VSCode-cfg-support#3]
(At least when using `bind`) backslashes don't actually escape the following character, resulting in broken syntax highlighting for the entire rest of the file after `"\"` (See screenshot).

<details><summary>backslash.cfg</summary>

```cfg
echo "Binding backslash in double quotes...";
bind "\" "echo If you see this, backslash syntax highlighting is improper.";
echo "Done.";

```
</details>

<details><summary>In-engine test (TF2, I don't own ETS/ETS2)</summary>

```cfg
] bind \ "echo example"
] bind \
"\" = "echo example"
] exec backslash.cfg
execing backslash.cfg
Binding backslash in double quotes... 
Done. 
] bind \
"\" = "echo If you see this, backslash syntax highlighting is improper."
```
</details>

![image](https://user-images.githubusercontent.com/18708515/164748124-f4e4a794-9d78-4e1d-a10a-f68d1ad9770f.png)

**Comment by joelcancela** [comment]
Extension updated
Let me know if you see other issues
Thanks for your feedback  :)
