### ISSUE TITLE
Periods/Full stops are always colored blue if they're in quotes.

### ISSUE THREAD

**Issue by femboyfin** [joelcancela/VSCode-cfg-support#4]
It's me again 😄, `.`s are blue regardless of what type the value in quotes is (float or otherwise).
I'm not familiar with how VSC syntax highlighting works but you might be able to regex the value in quotes to see if there's anything but numbers/`.` and then again to make sure it only has one `.` (to avoid false positive blue `.`s in version numbers ex `1.2.3`).

![image](https://user-images.githubusercontent.com/18708515/168676587-e041f0b7-70ff-46bd-912a-6e3db7e84da0.png)

*P.S. much love to you for making this in the first place, I've been using it for a long time before my first issue and it's a very helpful extension! ❤️*

**Comment by joelcancela** [comment]
Hi !
Good catch on this issue, update on the market will follow shortly

Thank you for your feedback I really appreciate it :)

Best regards
