### ISSUE TITLE
Numbers in quotes are always light green as of 0.3.0

### ISSUE THREAD

**Issue by femboyfin** [joelcancela/VSCode-cfg-support#5]
Numbers in quotes are always showing up as light green after updating to 0.3.0 (similarly to #4 with `.`s). 
![image](https://user-images.githubusercontent.com/18708515/168895674-61ad36a2-7be3-48ba-ab63-f85a8a6d1610.png)

**Comment by joelcancela** [comment]
This one I did it on purpose, I thought it would be great to have numbers highlighted when between quotes, but maybe I can make this less agressive and only highlight numbers when not surrounded by words for example

**Comment by joelcancela** [comment]
Reverted in 6d32139ee2701f2b0a30f1ecfd788c4d5e2f5e04 and published as 0.3.1

**Comment by femboyfin** [comment]
I do definitely agree with having them highlighted and making it a bit less aggressive.
I found it pretty useful in situations with aliases like this:
![image](https://user-images.githubusercontent.com/18708515/168898196-7ef06f0e-1e8a-4825-a6b1-d9d3d8d857ec.png)
However in other places like the examples in line 1 through 5, it's highlighting in a way I wasn't expecting. 
Only highlighting them as numbers if they're bordered on either side by quotes or whitespace might be a nice middleground?

**Comment by joelcancela** [comment]
> I do definitely agree with having them highlighted and making it a bit less aggressive. I found it pretty useful in situations with aliases like this: ![image](https://user-images.githubusercontent.com/18708515/168898196-7ef06f0e-1e8a-4825-a6b1-d9d3d8d857ec.png) However in other places like the examples in line 1 through 5, it's highlighting in a way I wasn't expecting. Only highlighting them as numbers if they're bordered on either side by quotes or whitespace might be a nice middleground?

I will implement this later, this looks like a good way :)

**Comment by joelcancela** [comment]
0.3.2 published with better number support, enjoy

**Comment by femboyfin** [comment]
Still having some unexpected results on 0.3.2 🤔
![image](https://user-images.githubusercontent.com/18708515/169307493-87cfb0af-c515-4e76-abe8-2aa8a655d142.png)
![image](https://user-images.githubusercontent.com/18708515/169309360-ab14c615-2219-4056-ac80-0d4877167703.png)

**Comment by joelcancela** [comment]
Another good catch, let's go 0.3.3
